# .devcontainer/Dockerfile.dev
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc-13 g++-13 \
    git \
    cmake \
    ninja-build \
    pkg-config \
    curl \
    wget \
    zip \
    unzip \
    tar \
    bison \
    flex \
    python3 \
    python3-pip \
    autoconf \
    automake \
    libtool \
    zlib1g-dev \
    liblz4-dev \
    libzstd-dev \
    ca-certificates \
    gdb \
    clangd \
    clang-format \
    clang-tidy \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

# vcpkg
WORKDIR /opt
RUN git clone https://github.com/microsoft/vcpkg.git
WORKDIR /opt/vcpkg
RUN git checkout 2026.06.01 && \
    ./bootstrap-vcpkg.sh -disableMetrics

ENV VCPKG_ROOT=/opt/vcpkg
ENV VCPKG_FORCE_SYSTEM_BINARIES=1

COPY vcpkg.json /tmp/
ENV VCPKG_MAX_CONCURRENCY=8
RUN cd /tmp && ${VCPKG_ROOT}/vcpkg install --triplet x64-linux

WORKDIR /workspace
